env:
  - CXX=g++-4.8
language: node_js
node_js:
  - '6'
  - '4'
  - '0.12'
  - '0.10'
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq librsvg2-dev
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
